# Generated by Django 4.2.5 on 2023-09-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(choices=[('neutral', 'Neutral'), ('like', 'Like'), ('decline', 'Decline'), ('match', 'Match')], default='neutral', max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('neutral', 'Neutral')], default='neutral', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
                ('profile', models.BooleanField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.users')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('id_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.likes')),
            ],
        ),
        migrations.AddField(
            model_name='likes',
            name='id_user_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='base.users'),
        ),
        migrations.AddField(
            model_name='likes',
            name='id_user_liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='base.users'),
        ),
    ]
