# Generated by Django 4.2.5 on 2023-09-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_users_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='messages',
            name='id_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.users'),
            preserve_default=False,
        ),
    ]
